export const RECOMMENDATION_TYPE = Object.freeze({
  ACTIVITY: 'activity',
  DESTINATION: 'destination',
  FOOD: 'food',
  ACCOMMODATION: 'accommodation',
  TRANSPORT: 'transport',
  SAFETY: 'safety',
  WEATHER_SUITABILITY: 'weather_suitability',
});

export const SCORE_FACTOR = Object.freeze({
  TRAVELLER_INTERESTS: 'traveller_interests',
  BUDGET: 'budget',
  TRIP_DURATION: 'trip_duration',
  ACTIVITY_PREFERENCES: 'activity_preferences',
  ACCESSIBILITY: 'accessibility',
  TRAVEL_PACE: 'travel_pace',
  CROWD_TOLERANCE: 'crowd_tolerance',
  CLIMATE_PREFERENCE: 'climate_preference',
  LANGUAGE_PREFERENCE: 'language_preference',
  TRANSPORT_PREFERENCE: 'transport_preference',
  RISK_TOLERANCE: 'risk_tolerance',
});

export const DEFAULT_SCORE_WEIGHTS = Object.freeze({
  [SCORE_FACTOR.TRAVELLER_INTERESTS]: 16,
  [SCORE_FACTOR.BUDGET]: 12,
  [SCORE_FACTOR.TRIP_DURATION]: 8,
  [SCORE_FACTOR.ACTIVITY_PREFERENCES]: 18,
  [SCORE_FACTOR.ACCESSIBILITY]: 10,
  [SCORE_FACTOR.TRAVEL_PACE]: 8,
  [SCORE_FACTOR.CROWD_TOLERANCE]: 8,
  [SCORE_FACTOR.CLIMATE_PREFERENCE]: 8,
  [SCORE_FACTOR.LANGUAGE_PREFERENCE]: 6,
  [SCORE_FACTOR.TRANSPORT_PREFERENCE]: 6,
  [SCORE_FACTOR.RISK_TOLERANCE]: 10,
});

export const RECOMMENDATION_AUDIT_ACTIONS = Object.freeze({
  RECOMMENDATIONS_GENERATED: 'RECOMMENDATIONS_GENERATED',
  RECOMMENDATION_EXPLAINED: 'RECOMMENDATION_EXPLAINED',
});
