/**
 * Report Builder
 *
 * Takes a completed OrchestrationResult + contextBus snapshot
 * and produces a structured Markdown execution report.
 */

export function buildReport(orchResult, contextBus, request) {
  const now = new Date().toISOString();
  const lines = [];

  const icon = orchResult.outcome === 'completed' ? '✓'
    : orchResult.outcome === 'partial'   ? '◑'
    : orchResult.outcome === 'dry_run'   ? '◻'
    : '✗';

  lines.push(`# Orchestration Execution Report`);
  lines.push(``);
  lines.push(`*Generated: ${now}*`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // ── Summary ─────────────────────────────────────────────────────────────────
  lines.push(`## ${icon} Summary`);
  lines.push(``);
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Request** | ${escMd(request?.rawMessage ?? 'n/a')} |`);
  lines.push(`| **Outcome** | ${orchResult.outcome.toUpperCase()} |`);
  lines.push(`| **Duration** | ${orchResult.durationMs}ms |`);
  lines.push(`| **Orchestration ID** | \`${orchResult.orchestrationId}\` |`);
  lines.push(`| **Plan ID** | \`${orchResult.planId}\` |`);
  lines.push(``);

  // Entities
  if (request?.entities && Object.keys(request.entities).length > 0) {
    lines.push(`**Detected entities:** ${Object.entries(request.entities).map(([k, v]) => `${k}: **${v}**`).join(' · ')}`);
    lines.push(``);
  }

  if (request?.intentSignals?.length) {
    lines.push(`**Intent signals:** ${request.intentSignals.join(', ')}`);
    lines.push(``);
  }

  // ── Engine results ───────────────────────────────────────────────────────────
  lines.push(`## Engine Execution`);
  lines.push(``);
  lines.push(`| Engine | Status | Duration | Attempts | Summary |`);
  lines.push(`|--------|--------|----------|----------|---------|`);

  for (const [name, result] of Object.entries(orchResult.engineResults)) {
    const status = result.skipped  ? '○ Skipped'
      : result.success ? '✓ OK'
      : '✗ Failed';
    const duration = result.durationMs > 0 ? `${result.durationMs}ms` : '—';
    const attempts = result.attempts > 1 ? `${result.attempts} (retried)` : String(result.attempts || '—');
    const summary  = escMd(result.summary?.slice(0, 80) ?? '');
    lines.push(`| **${name}** | ${status} | ${duration} | ${attempts} | ${summary} |`);
  }
  lines.push(``);

  // ── Phase timeline ───────────────────────────────────────────────────────────
  lines.push(`## Execution Timeline`);
  lines.push(``);
  for (const phase of (orchResult.phaseResults ?? [])) {
    const phaseIcon = phase.success ? '✓' : '✗';
    lines.push(`### ${phaseIcon} Phase ${phase.phaseIndex + 1} (${phase.durationMs}ms)`);
    lines.push(``);
    for (const r of phase.results) {
      const icon2  = r.skipped ? '○' : r.success ? '✓' : '✗';
      const retried = r.attempts > 1 ? ` *(${r.attempts} attempts)*` : '';
      lines.push(`- ${icon2} **${r.engineName}**${retried} — ${escMd(r.summary?.slice(0, 120) ?? '')}`);

      if (r.evidence?.length) {
        for (const ev of r.evidence.slice(0, 4)) {
          lines.push(`  - ${escMd(String(ev).slice(0, 100))}`);
        }
      }

      if (r.error) {
        lines.push(`  - ⚠ Error: ${escMd(r.error.slice(0, 100))}`);
      }
    }
    lines.push(``);
  }

  // ── Context bus ──────────────────────────────────────────────────────────────
  if (contextBus) {
    lines.push(`## Context Bus — Shared Data`);
    lines.push(``);
    lines.push(`| Key | Source Engine | Contents |`);
    lines.push(`|-----|---------------|---------|`);

    for (const row of contextBus.toReport()) {
      lines.push(`| \`${row.key}\` | ${row.source} | ${escMd(row.description)} |`);
    }
    lines.push(``);
  }

  // ── Notable outputs ──────────────────────────────────────────────────────────
  const notableEngines = Object.entries(orchResult.engineResults)
    .filter(([, r]) => r.success && r.data && !r.skipped && r.evidence?.length > 0);

  if (notableEngines.length > 0) {
    lines.push(`## Notable Outputs`);
    lines.push(``);
    for (const [name, result] of notableEngines) {
      lines.push(`### ${name}`);
      lines.push(``);
      for (const ev of (result.evidence ?? []).slice(0, 5)) {
        lines.push(`- ${escMd(String(ev).slice(0, 150))}`);
      }
      lines.push(``);
    }
  }

  // ── Warnings ─────────────────────────────────────────────────────────────────
  const warnings = (orchResult.warnings ?? []).filter(Boolean);
  if (warnings.length > 0) {
    lines.push(`## Warnings`);
    lines.push(``);
    for (const w of warnings) {
      lines.push(`- ⚠ ${escMd(w)}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Report generated by Coach's Eye Orchestrator*`);

  return lines.join('\n');
}

function escMd(s) {
  return String(s ?? '').replace(/\|/g, '\\|');
}
