// Approval card factory — creates structured approval items from engine outputs.
import { randomUUID } from 'crypto';

const RISK_ICON = { low: '🟢', medium: '🟡', high: '🔴' };
const STATUS_ICON = { pending: '⏳', approved: '✅', rejected: '❌', archived: '📦' };
const ENGINE_LABELS = {
  'communications-engine': 'Communications Engine',
  'workflow-engine':        'Workflow Engine',
  'coaching-engine':        'Coaching Engine',
  'club-intelligence':      'Club Intelligence',
  'player-development':     'Player Development',
  'ai-copilot':             'AI Copilot',
  'orchestrator':           'Orchestrator',
};

export function createCard(options = {}) {
  const {
    type, title, generatedBy, confidence = 80,
    evidence = [], preview = {}, riskLevel = 'low',
    requiresRole = 'coach', metadata = {},
  } = options;

  return {
    approvalId:  randomUUID(),
    type:        type ?? 'unknown',
    title:       title ?? (type ?? 'item').replace(/_/g, ' '),
    generatedBy: generatedBy ?? 'unknown',
    confidence,
    evidence,
    preview,
    riskLevel,
    requiresRole,
    metadata,
  };
}

// Create cards from Communications Engine draft batch.
export function cardsFromCommsDrafts(drafts = []) {
  return drafts.map(d => createCard({
    type:        d.type,
    title:       d.content?.subject ?? d.type?.replace(/_/g, ' '),
    generatedBy: 'communications-engine',
    confidence:  90,
    evidence:    d.riskNotes ?? [],
    preview:     { subject: d.content?.subject, body: (d.content?.body ?? '').slice(0, 300), audienceSummary: d.audienceSummary },
    riskLevel:   d.riskLevel ?? 'low',
    requiresRole: d.riskLevel === 'high' ? 'manager' : 'coach',
    metadata:    { channel: d.channel, recipientCount: d.recipientCount, isMock: d.isMock },
  }));
}

// Create a card from a Workflow Engine run result.
export function cardFromWorkflow(result, workflowName) {
  const conf = result.outcome === 'completed' ? 92 : result.outcome === 'partial' ? 65 : 40;
  return createCard({
    type:        'workflow_result',
    title:       `Workflow: ${workflowName ?? result.workflowId ?? 'Run'}`,
    generatedBy: 'workflow-engine',
    confidence:  conf,
    evidence:    result.warnings ?? [],
    preview:     { summary: result.summary ?? `Outcome: ${result.outcome}`, durationMs: result.durationMs },
    riskLevel:   result.outcome === 'failed' ? 'high' : 'low',
    requiresRole:'coach',
    metadata:    { workflowId: result.workflowId, outcome: result.outcome },
  });
}

// Create a card from a Copilot AI suggestion.
export function cardFromCopilot(response) {
  return createCard({
    type:        'ai_suggestion',
    title:       `AI Suggestion: ${(response.summary ?? response.intent ?? 'Recommendation').slice(0, 60)}`,
    generatedBy: 'ai-copilot',
    confidence:  response.confidence ?? 75,
    evidence:    response.evidence ?? [],
    preview:     { summary: response.summary ?? '', data: response.data },
    riskLevel:   'low',
    requiresRole:'coach',
    metadata:    { tools: response.toolsUsed ?? [] },
  });
}

export function formatCard(card) {
  const risk    = RISK_ICON[card.riskLevel] ?? '⚪';
  const status  = STATUS_ICON[card.status ?? 'pending'] ?? '⏳';
  const engine  = ENGINE_LABELS[card.generatedBy] ?? card.generatedBy;
  const conf    = `${card.confidence ?? '?'}%`;

  const evidenceBlock = (card.evidence ?? []).length > 0
    ? card.evidence.map(e => `  - ${e}`).join('\n')
    : '  - No evidence provided';

  const previewBlock = card.preview?.subject
    ? `**Subject:** ${card.preview.subject}\n**Preview:** ${(card.preview.body ?? card.preview.summary ?? '').slice(0, 200)}…`
    : card.preview?.summary
    ? `**Summary:** ${(card.preview.summary ?? '').slice(0, 300)}`
    : '_No preview available_';

  return `#### ${status} ${card.title}

| Field | Value |
|-------|-------|
| **ID** | \`${card.approvalId}\` |
| **Type** | ${card.type?.replace(/_/g, ' ')} |
| **Generated by** | ${engine} |
| **Confidence** | ${conf} |
| **Risk** | ${risk} ${card.riskLevel?.toUpperCase()} |
| **Requires** | ${card.requiresRole}+ |
| **Status** | ${card.status ?? 'pending'} |

**Evidence:**
${evidenceBlock}

${previewBlock}

${card.editedContent ? '> ✏️ **Content has been edited**\n' : ''}
**Actions:** \`approve\` | \`reject\` | \`edit\` | \`archive\`

---`;
}
