export const TRIP_STATUS = Object.freeze({
  DRAFT: 'draft',
  PLANNED: 'planned',
  ACTIVE: 'active',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
});

export const TRIP_VISIBILITY = Object.freeze({
  PRIVATE: 'private',
  APPROXIMATE_AREA: 'approximate_area',
  PUBLIC_TO_JOINED_CONTEXTS: 'public_to_joined_contexts',
});

export const TRIP_AUDIT_ACTIONS = Object.freeze({
  TRIP_CREATED: 'TRIP_CREATED',
  TRIP_UPDATED: 'TRIP_UPDATED',
  TRIP_DATES_CHANGED: 'TRIP_DATES_CHANGED',
  TRIP_DESTINATION_CHANGED: 'TRIP_DESTINATION_CHANGED',
  TRIP_VISIBILITY_CHANGED: 'TRIP_VISIBILITY_CHANGED',
  TRIP_STARTED: 'TRIP_STARTED',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  TRIP_CANCELLED: 'TRIP_CANCELLED',
  TRIP_READ: 'TRIP_READ',
});

export const TERMINAL_TRIP_STATUSES = Object.freeze([
  TRIP_STATUS.COMPLETED,
  TRIP_STATUS.CANCELLED,
]);

