// Today's Tasks widget — everything requiring action across all engines.

import { fetchUpcomingSessions } from '../adapters/memory-adapter.js';
import { fetchPendingWorkflows } from '../adapters/workflow-adapter.js';
import { fetchMembershipAlerts } from '../adapters/data-adapter.js';
import { getPending } from '../approval-centre/approval-queue.js';

const TASK_PRIORITY = { critical: 0, high: 1, medium: 2, low: 3 };

export async function buildTodaysTasks(role = 'coach') {
  const [sessions, workflows, membership] = await Promise.all([
    fetchUpcomingSessions(),
    fetchPendingWorkflows(),
    fetchMembershipAlerts(),
  ]);

  const pendingApprovals = getPending();
  const tasks = [];

  // Approval centre tasks
  pendingApprovals.forEach(a => {
    tasks.push({
      id:       `approval-${a.approvalId}`,
      source:   'approval-centre',
      priority: a.riskLevel === 'high' ? 'critical' : a.riskLevel === 'medium' ? 'high' : 'medium',
      type:     'approval',
      text:     `Review & approve: ${a.title ?? a.type}`,
      detail:   `Generated by ${a.generatedBy} — ${a.riskLevel} risk`,
      action:   'approve / reject / edit',
      data:     { approvalId: a.approvalId, type: a.type },
    });
  });

  // Upcoming training sessions
  sessions.sessions.forEach(s => {
    tasks.push({
      id:       `session-${s.id}`,
      source:   'coaching-engine',
      priority: 'high',
      type:     'training',
      text:     `${s.ageGroup ?? 'Squad'} training: ${s.focus ?? 'General'}`,
      detail:   `${s.durationMinutes ?? 90} mins · ${s.venue ?? 'Club Grounds'}`,
      action:   'confirm attendance / send reminder',
      data:     s,
    });
  });

  // Pending workflow steps
  workflows.pending.forEach(w => {
    tasks.push({
      id:       `workflow-${w.queueId}`,
      source:   'workflow-engine',
      priority: 'medium',
      type:     'workflow',
      text:     `Workflow queued: ${w.name ?? w.workflowDef?.name ?? 'Unnamed'}`,
      detail:   `Scheduled for ${w.scheduledFor ? new Date(w.scheduledFor).toLocaleString('en-IE') : 'now'}`,
      action:   'execute / cancel',
      data:     w,
    });
  });

  // Membership actions
  membership.expiringSoon.forEach(m => {
    tasks.push({
      id:       `renewal-${m.id ?? m.playerId}`,
      source:   'data-integration',
      priority: 'medium',
      type:     'membership',
      text:     `Renewal due: ${m.playerName ?? m.name} (${m.membershipType})`,
      detail:   `Expires ${m.validUntil ? new Date(m.validUntil).toLocaleDateString('en-IE') : 'soon'}`,
      action:   'send renewal reminder',
      data:     m,
    });
  });

  membership.pending.forEach(m => {
    tasks.push({
      id:       `pending-${m.id ?? m.playerId}`,
      source:   'data-integration',
      priority: 'medium',
      type:     'membership',
      text:     `Process membership: ${m.playerName ?? m.name}`,
      detail:   `Status: pending · Type: ${m.membershipType}`,
      action:   'activate membership',
      data:     m,
    });
  });

  // Sort by priority
  tasks.sort((a, b) => (TASK_PRIORITY[a.priority] ?? 3) - (TASK_PRIORITY[b.priority] ?? 3));

  const byCat = {};
  tasks.forEach(t => { byCat[t.type] = (byCat[t.type] ?? 0) + 1; });

  return {
    tasks,
    total:    tasks.length,
    critical: tasks.filter(t => t.priority === 'critical').length,
    byType:   byCat,
    isMock:   sessions.isMock || membership.isMock,
  };
}

export function formatTodaysTasks(widget) {
  const grouped = {};
  widget.tasks.forEach(t => { (grouped[t.priority] = grouped[t.priority] ?? []).push(t); });

  const priorityLabel = { critical: '🔴 Critical', high: '🟠 High Priority', medium: '🟡 Medium', low: '🟢 Low' };
  let out = `## Today's Tasks (${widget.total})\n\n`;

  for (const level of ['critical', 'high', 'medium', 'low']) {
    const items = grouped[level];
    if (!items?.length) continue;
    out += `### ${priorityLabel[level]}\n`;
    items.forEach(t => {
      out += `- **${t.text}**\n`;
      out += `  _${t.detail}_ · Action: \`${t.action}\`\n`;
    });
    out += '\n';
  }
  return out;
}
