/**
 * Intelligence Timeline — Mock Seed Data
 *
 * 40 realistic events spanning the last 90 days for an Irish rugby club.
 * Seeded on first access when the store is empty.
 * Covers all 7 recommendation categories, multiple statuses, teams, players,
 * and fixtures — demonstrating the full filtering surface.
 *
 * All timestamps are relative to the time this module is first imported
 * (daysAgo helper) so the data always looks "recent" regardless of when
 * the club first runs the service.
 */

import { randomUUID } from 'crypto';

export const TEAMS = {
  SENIOR_A:  { id: 'team-senior-a',  name: 'Senior A' },
  SENIOR_B:  { id: 'team-senior-b',  name: 'Senior B' },
  U20:       { id: 'team-u20',       name: 'Under 20s' },
  U18:       { id: 'team-u18',       name: 'Under 18s' },
};

export const PLAYERS = {
  JACK:   { id: 'p-jack-os',    name: 'Jack O\'Sullivan',  teamId: 'team-senior-a' },
  ROSS:   { id: 'p-ross-d',     name: 'Ross Dunne',        teamId: 'team-senior-a' },
  CONOR:  { id: 'p-conor-l',    name: 'Conor Lynch',       teamId: 'team-senior-a' },
  SEAN:   { id: 'p-sean-h',     name: 'Séan Hennessy',     teamId: 'team-senior-b' },
  LIAM:   { id: 'p-liam-c',     name: 'Liam Carroll',      teamId: 'team-u20' },
};

export const FIXTURES = {
  FIX_1: { id: 'fix-naas',      summary: 'vs Naas RFC — League' },
  FIX_2: { id: 'fix-bective',   summary: 'vs Bective Rangers — Cup' },
  FIX_3: { id: 'fix-terenure',  summary: 'vs Terenure College — League' },
  FIX_4: { id: 'fix-clontarf',  summary: 'vs Clontarf RFC — League' },
};

function daysAgo(n) {
  return new Date(Date.now() - n * 86400000).toISOString();
}

function event(fields) {
  return {
    id:              randomUUID(),
    timestamp:       fields.timestamp ?? daysAgo(0),
    engine:          fields.engine ?? 'recommendation-engine',
    recommendationId: fields.recommendationId ?? randomUUID(),
    category:        fields.category,
    priority:        fields.priority,
    confidence:      fields.confidence ?? 75,
    title:           fields.title,
    description:     fields.description,
    explanation:     fields.explanation,
    action:          fields.action,
    source:          fields.source ?? 'mock',
    status:          fields.status ?? 'new',
    acknowledgedAt:  fields.status === 'acknowledged' || fields.status === 'completed' || fields.status === 'ignored'
                       ? daysAgo(Math.max(0, (fields._ackDaysAgo ?? 0))) : null,
    completedAt:     fields.status === 'completed' ? daysAgo(Math.max(0, (fields._completeDaysAgo ?? 0))) : null,
    ignoredAt:       fields.status === 'ignored'   ? daysAgo(Math.max(0, (fields._ignoreDaysAgo ?? 0))) : null,
    notes:           fields.notes ?? null,
    teamId:          fields.teamId ?? null,
    teamName:        fields.teamName ?? null,
    playerId:        fields.playerId ?? null,
    playerName:      fields.playerName ?? null,
    fixtureId:       fields.fixtureId ?? null,
    fixtureSummary:  fields.fixtureSummary ?? null,
    seasonPhase:     fields.seasonPhase ?? 'COMPETITIVE',
  };
}

export function buildSeedEvents() {
  return [

    // ── Week 1 (3 months ago) — PRE-SEASON ────────────────────────────────────
    event({
      timestamp:   daysAgo(89),
      category:    'Training',
      priority:    'MEDIUM',
      confidence:  70,
      title:       'Pre-season attendance at 74% — base fitness at risk',
      description: 'Senior A turnout at 74% in week 1 of pre-season. Early absence patterns tend to persist through the season.',
      explanation: 'Pre-season turnout below 85% triggers this because base fitness built now directly influences competitive-phase performance.',
      action:      'Communicate the importance of pre-season commitment to all players.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'PRE_SEASON',
      status:      'completed',
      _ackDaysAgo: 88,
      _completeDaysAgo: 85,
      notes:       'Sent WhatsApp blast — attendance improved to 86% by week 3.',
    }),

    event({
      timestamp:   daysAgo(87),
      category:    'Player Welfare',
      priority:    'HIGH',
      confidence:  80,
      title:       'Under 18s — 4 youth players above recommended weekly session limit',
      description: 'Liam Carroll, Darragh Walsh, Rory Quinn, and Cian Murphy logged 4+ sessions in week 1. Youth athletes require mandatory rest days.',
      explanation: 'Youth players (U18 and below) are flagged when session count exceeds 3 per week due to growth-plate injury risk.',
      action:      'Remove these players from Thursday\'s additional conditioning session. Notify parents.',
      teamId:      TEAMS.U18.id,
      teamName:    TEAMS.U18.name,
      playerId:    PLAYERS.LIAM.id,
      playerName:  PLAYERS.LIAM.name,
      seasonPhase: 'PRE_SEASON',
      status:      'completed',
      _ackDaysAgo: 87,
      _completeDaysAgo: 86,
      notes:       'Session modified. Parents notified via app.',
    }),

    event({
      timestamp:   daysAgo(84),
      category:    'Medical',
      priority:    'MEDIUM',
      confidence:  65,
      title:       '3 active injuries entering pre-season competitive block',
      description: 'Jack O\'Sullivan (hamstring), Conor Lynch (knee), and Ross Dunne (shoulder) all carrying injuries into the first contact block.',
      explanation: 'When 3+ active injuries are recorded simultaneously, a medical review is raised to check for systemic causes (overtraining, pitch conditions, warm-up protocols).',
      action:      'Review training load data for the previous 3 weeks. Flag cluster to medical officer.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'PRE_SEASON',
      status:      'acknowledged',
      _ackDaysAgo: 83,
      notes:       'Medical officer reviewed — no systemic cause identified. Isolated incidents.',
    }),

    event({
      timestamp:   daysAgo(82),
      category:    'Performance',
      priority:    'MEDIUM',
      confidence:  78,
      title:       'Pre-season phase: recommended focus — Aerobic base, structural fitness',
      description: 'You are in the pre-season phase. Evidence-based prescription: aerobic base (GPS volume), structural conditioning, and system introduction.',
      explanation: 'Season intelligence maps the current date to the pre-season phase and generates a training prescription based on rugby periodisation models.',
      action:      'Align next 4 sessions with aerobic base emphasis. Cap contact sessions at 1 per week.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'PRE_SEASON',
      status:      'acknowledged',
      _ackDaysAgo: 82,
    }),

    // ── Week 4 (2 months ago) — PRE-SEASON LATE ───────────────────────────────
    event({
      timestamp:   daysAgo(62),
      category:    'Selection',
      priority:    'HIGH',
      confidence:  85,
      title:       '2 Prop players unavailable — 5d to first pre-season fixture',
      description: 'Jack O\'Sullivan and Conor Lynch are both unavailable for the pre-season opener vs Naas RFC.',
      explanation: 'Two players unavailable in the same position creates a structural gap. Selection action needed when positional group drops below minimum cover.',
      action:      'Review squad depth at Prop. Consider repositioning or calling up cover.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      playerId:    PLAYERS.JACK.id,
      playerName:  PLAYERS.JACK.name,
      fixtureId:   FIXTURES.FIX_1.id,
      fixtureSummary: FIXTURES.FIX_1.summary,
      seasonPhase: 'PRE_SEASON',
      status:      'completed',
      _ackDaysAgo: 62,
      _completeDaysAgo: 61,
      notes:       'Moved Cormac to loosehead. Called up Fionn from Senior B.',
    }),

    event({
      timestamp:   daysAgo(60),
      category:    'Club',
      priority:    'MEDIUM',
      confidence:  68,
      title:       'Member engagement score 54/100 — communication review needed',
      description: 'Engagement across digital touchpoints has dropped to 54/100. Members are less active in the app and email open rates are down.',
      explanation: 'Engagement is the leading indicator for renewal and retention, typically falling 4–6 weeks before membership lapses accelerate.',
      action:      'Schedule a newsletter and launch a pre-season community event.',
      teamId:      null,
      seasonPhase: 'PRE_SEASON',
      status:      'completed',
      _ackDaysAgo: 59,
      _completeDaysAgo: 55,
      notes:       'Pre-season newsletter sent. Open rate 61% — above average.',
    }),

    // ── Week 6-8 (5-6 weeks ago) — COMPETITIVE SEASON BEGINS ─────────────────
    event({
      timestamp:   daysAgo(44),
      category:    'Medical',
      priority:    'HIGH',
      confidence:  92,
      title:       'Ross Dunne — concussion protocol active, not cleared for contact',
      description: 'Ross Dunne received a head impact in Friday\'s training session. Concussion assessment completed — currently in Return-to-Play step 2.',
      explanation: 'Any HIGH severity medical alert triggers this recommendation because contact clearance is a statutory safeguarding requirement.',
      action:      'Contact medical officer. Update Ross\'s status before next training session. Do not permit contact until step 5 clearance.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      playerId:    PLAYERS.ROSS.id,
      playerName:  PLAYERS.ROSS.name,
      fixtureId:   FIXTURES.FIX_2.id,
      fixtureSummary: FIXTURES.FIX_2.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 44,
      _completeDaysAgo: 37,
      notes:       'RTP protocol followed. Ross cleared for contact 7 days later. Missed Bective fixture.',
    }),

    event({
      timestamp:   daysAgo(43),
      category:    'Performance',
      priority:    'MEDIUM',
      confidence:  80,
      title:       'Competitive season: recommended focus — Game shape, Set-piece refinement',
      description: 'You are in the competitive season phase. Prescription: reduce volume, increase specificity. Focus on game patterns and set-piece.',
      explanation: 'Season intelligence tracks your club\'s position and maps it to competitive-phase prescriptions. Volume should decrease as match frequency increases.',
      action:      'Run one pattern session and one defensive session before each matchday.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'acknowledged',
      _ackDaysAgo: 42,
    }),

    event({
      timestamp:   daysAgo(40),
      category:    'Logistics',
      priority:    'MEDIUM',
      confidence:  60,
      title:       'Heavy rain forecast — reduce kicking volume',
      description: 'Heavy rain forecast for Thursday and Friday training windows ahead of Saturday vs Bective Rangers.',
      explanation: 'Weather risk above CLEAR triggers logistics recommendations. Heavy rain makes kicking practice less effective and can reinforce poor technique.',
      action:      'Move kicking sessions to the sports hall. Prioritise contact and defensive shape work.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      fixtureId:   FIXTURES.FIX_2.id,
      fixtureSummary: FIXTURES.FIX_2.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'ignored',
      _ignoreDaysAgo: 40,
      notes:       'Hall not available. Went ahead outdoors — no issues.',
    }),

    event({
      timestamp:   daysAgo(38),
      category:    'Training',
      priority:    'MEDIUM',
      confidence:  82,
      title:       'Match week: reduce training load to protect freshness',
      description: 'Fixture vs Bective Rangers is 3 days away. This is the optimal window to taper training intensity.',
      explanation: 'Season intelligence detects match-week prep (3d to kickoff). Load reduction is recommended automatically in the final 3 days before any fixture.',
      action:      'Cap session length to 60 min. Focus on shape and set-pieces. No contact above 50%.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      fixtureId:   FIXTURES.FIX_2.id,
      fixtureSummary: FIXTURES.FIX_2.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 38,
      _completeDaysAgo: 35,
    }),

    // ── Week 9-10 (4 weeks ago) ───────────────────────────────────────────────
    event({
      timestamp:   daysAgo(35),
      category:    'Performance',
      priority:    'HIGH',
      confidence:  65,
      title:       '2 losses in last 3 matches — tactical review recommended',
      description: 'Last 3 results: L 7-22, L 14-19, W 18-12. Two consecutive defeats before the win suggest a systematic issue.',
      explanation: 'When 2+ losses appear in a 3-match window, the pattern is flagged as potentially systematic rather than one-off.',
      action:      'Schedule a coaches\' video review. Identify one recurring theme and address it in the next two training sessions.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 35,
      _completeDaysAgo: 30,
      notes:       'Video review: defensive line speed. Addressed in 2 sessions. Won next match 23-10.',
    }),

    event({
      timestamp:   daysAgo(33),
      category:    'Training',
      priority:    'MEDIUM',
      confidence:  72,
      title:       'Senior B attendance has dropped 22% this month',
      description: 'Senior B average attendance is 61% this month, down from 83% last month.',
      explanation: 'Attendance engine is tracking a 22% decline in Senior B training turnout. Fires when attendance falls below 80% or shows consistent downward trend.',
      action:      'Run an attendance communication. Investigate scheduling conflicts with the coaching group.',
      teamId:      TEAMS.SENIOR_B.id,
      teamName:    TEAMS.SENIOR_B.name,
      seasonPhase: 'COMPETITIVE',
      status:      'acknowledged',
      _ackDaysAgo: 32,
      notes:       'Coaching group believes Tuesday session clashes with GAA. Considering time change.',
    }),

    event({
      timestamp:   daysAgo(30),
      category:    'Player Welfare',
      priority:    'MEDIUM',
      confidence:  70,
      title:       'Séan Hennessy flagged at welfare risk — attendance 48%',
      description: 'Séan Hennessy\'s attendance has dropped to 48% over the last 6 weeks. The digital twin has assigned a high retention-risk score.',
      explanation: 'The digital twin assigns welfare risk scores based on attendance, injury history, and engagement signals. Players crossing the high-risk threshold trigger this.',
      action:      'Make direct contact with Séan this week. Log any welfare notes in the player profile.',
      teamId:      TEAMS.SENIOR_B.id,
      teamName:    TEAMS.SENIOR_B.name,
      playerId:    PLAYERS.SEAN.id,
      playerName:  PLAYERS.SEAN.name,
      seasonPhase: 'COMPETITIVE',
      status:      'acknowledged',
      _ackDaysAgo: 29,
      notes:       'Spoke with Séan — work pressures. Will return after project deadline.',
    }),

    event({
      timestamp:   daysAgo(28),
      category:    'Selection',
      priority:    'HIGH',
      confidence:  88,
      title:       '2 Lock players unavailable — 6d to Terenure fixture',
      description: 'Fionn Brennan (work commitment) and Ciarán Kelly (hamstring) are unavailable for the Terenure match.',
      explanation: 'Two players unavailable in the same position 6 days out triggers HIGH-priority selection action.',
      action:      'Review lineout options. Consider promoting Under 20s cover player.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      fixtureId:   FIXTURES.FIX_3.id,
      fixtureSummary: FIXTURES.FIX_3.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 28,
      _completeDaysAgo: 26,
      notes:       'Promoted Aaron McCarthy (U20s). Lineout functioned well.',
    }),

    event({
      timestamp:   daysAgo(26),
      category:    'Logistics',
      priority:    'HIGH',
      confidence:  85,
      title:       'Back-to-back fixtures 6d apart — manage squad load',
      description: 'Terenure (Sat) and Clontarf (following Fri) are only 6 days apart. Players in both squads need active load management.',
      explanation: 'Fixture engine detects two upcoming fixtures within a 7-day window. Load management is triggered for gaps of 7 days or less.',
      action:      'Create A/B squad rotation. Limit full-contact training between fixtures. Prioritise recovery.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      fixtureId:   FIXTURES.FIX_3.id,
      fixtureSummary: FIXTURES.FIX_3.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 26,
      _completeDaysAgo: 20,
      notes:       'Rotated 6 players for Clontarf. Managed well — no fatigue injuries.',
    }),

    // ── Week 11-12 (2-3 weeks ago) ────────────────────────────────────────────
    event({
      timestamp:   daysAgo(22),
      category:    'Medical',
      priority:    'MEDIUM',
      confidence:  75,
      title:       'Conor Lynch returning from injury near match day',
      description: 'Conor Lynch is due to return from his knee injury 4 days before the Clontarf fixture. Returning players carry elevated re-injury risk in the first 2 sessions back.',
      explanation: 'Injury register shows a player with a return date that coincides with the fixture window. Re-injury risk is highest in the first week back.',
      action:      'Apply graduated return-to-play protocol. No full contact until medical clearance.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      playerId:    PLAYERS.CONOR.id,
      playerName:  PLAYERS.CONOR.name,
      fixtureId:   FIXTURES.FIX_4.id,
      fixtureSummary: FIXTURES.FIX_4.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 22,
      _completeDaysAgo: 18,
      notes:       'Conor cleared for contact 48h before match. Started as sub.',
    }),

    event({
      timestamp:   daysAgo(19),
      category:    'Club',
      priority:    'HIGH',
      confidence:  70,
      title:       'Club health score 56/100 — below healthy threshold',
      description: 'The Club Intelligence score has fallen to 56/100. The weakest dimension is engagement at 49/100.',
      explanation: 'The Club Intelligence engine continuously models club health across multiple dimensions. A score below 65/100 triggers an early-warning recommendation.',
      action:      'Review the Club Intelligence dashboard. Focus improvement efforts on the engagement dimension.',
      teamId:      null,
      seasonPhase: 'COMPETITIVE',
      status:      'acknowledged',
      _ackDaysAgo: 18,
      notes:       'Committee meeting scheduled to review member engagement strategy.',
    }),

    event({
      timestamp:   daysAgo(17),
      category:    'Training',
      priority:    'MEDIUM',
      confidence:  80,
      title:       'Match week: reduce training load to protect freshness',
      description: 'Fixture vs Clontarf RFC is 4 days away. Optimal taper window.',
      explanation: 'Season intelligence detects match-week prep (4d to kickoff). Load reduction recommended in the final 3 days before any fixture.',
      action:      'Cap session at 60 min. Set-pieces and shape only. No contact above 50%.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      fixtureId:   FIXTURES.FIX_4.id,
      fixtureSummary: FIXTURES.FIX_4.summary,
      seasonPhase: 'COMPETITIVE',
      status:      'completed',
      _ackDaysAgo: 17,
      _completeDaysAgo: 13,
    }),

    event({
      timestamp:   daysAgo(14),
      category:    'Performance',
      priority:    'LOW',
      confidence:  60,
      title:       'Three consecutive wins — protect mental freshness',
      description: 'Wins vs Terenure (23-10), Clontarf (17-14), and Naas (21-7). A winning run can create complacency in training.',
      explanation: 'Three consecutive wins trigger a low-priority reminder to help coaches avoid complacency and maintain process focus.',
      action:      'Run a session focused on areas of improvement. Set new micro-targets rather than celebrating past wins.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'acknowledged',
      _ackDaysAgo: 13,
    }),

    // ── This week (current) ───────────────────────────────────────────────────
    event({
      timestamp:   daysAgo(6),
      category:    'Selection',
      priority:    'HIGH',
      confidence:  87,
      title:       '2 Prop players unavailable — 5d to kickoff',
      description: 'Jack O\'Sullivan (hamstring) and Conor Lynch (knee, precautionary) are listed as unavailable for Saturday\'s fixture.',
      explanation: 'Fixture squad status shows 2 players unavailable in the same position (Prop) within match week. Positional shortage below minimum cover requires immediate selection action.',
      action:      'Review squad depth at Prop. Consider repositioning or calling up cover from the development squad.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      playerId:    PLAYERS.JACK.id,
      playerName:  PLAYERS.JACK.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(5),
      category:    'Medical',
      priority:    'HIGH',
      confidence:  92,
      title:       '1 high-severity medical alert — immediate review required',
      description: 'Ross Dunne has an active concussion protocol flag. Not cleared for contact.',
      explanation: 'Any HIGH severity medical alert triggers this because contact clearance is a safeguarding requirement.',
      action:      'Contact the club\'s medical officer today. Update Ross\'s status before the next training session.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      playerId:    PLAYERS.ROSS.id,
      playerName:  PLAYERS.ROSS.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(4),
      category:    'Training',
      priority:    'MEDIUM',
      confidence:  72,
      title:       'Training attendance has dropped 18% this month',
      description: 'Average club-wide attendance is 71%. Senior A lowest at 63%.',
      explanation: 'Attendance engine tracking a 18% decline in average training turnout. Fires when attendance falls below 80% or shows a consistent downward trend.',
      action:      'Run attendance communication to all teams. Investigate scheduling conflicts.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(3),
      category:    'Player Welfare',
      priority:    'MEDIUM',
      confidence:  70,
      title:       '1 player flagged at welfare risk',
      description: 'Séan Hennessy has been flagged again. Attendance has not recovered since the last check-in.',
      explanation: 'Digital twin welfare risk scoring re-flagged Séan after attendance remained below 50% for 3 consecutive weeks.',
      action:      'Make direct contact with Séan this week. Consider a pastoral conversation, not just a training reminder.',
      teamId:      TEAMS.SENIOR_B.id,
      teamName:    TEAMS.SENIOR_B.name,
      playerId:    PLAYERS.SEAN.id,
      playerName:  PLAYERS.SEAN.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(2),
      category:    'Club',
      priority:    'MEDIUM',
      confidence:  68,
      title:       'Club health score 58/100 — below healthy threshold',
      description: 'Engagement 52/100, attendance 68/100, governance 71/100, finance 61/100.',
      explanation: 'Club Intelligence score below 65/100 triggers this early warning. Engagement remains the weakest dimension.',
      action:      'Review the Club Intelligence dashboard. Prioritise engagement improvement.',
      teamId:      null,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(1),
      category:    'Performance',
      priority:    'MEDIUM',
      confidence:  80,
      title:       'Season phase: Competitive Season — recommended focus: Game shape, Set-piece refinement',
      description: 'Mid-competitive phase. Prescription: maintain competitive fitness, sharpen game patterns. Run one pattern session and one defensive session per match week.',
      explanation: 'Season intelligence maps current date to competitive phase prescription. Volume should decrease as match frequency holds steady.',
      action:      'Align next 2 sessions with set-piece refinement and defensive organisation.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),

    event({
      timestamp:   daysAgo(0),
      category:    'Logistics',
      priority:    'MEDIUM',
      confidence:  60,
      title:       'Heavy rain forecast — reduce kicking volume',
      description: 'Heavy rain forecast for Thursday and Friday training windows.',
      explanation: 'Weather risk above CLEAR for the training window. Heavy rain makes kicking practice less effective.',
      action:      'Move kicking sessions indoors or postpone. Prioritise contact and defensive shape.',
      teamId:      TEAMS.SENIOR_A.id,
      teamName:    TEAMS.SENIOR_A.name,
      seasonPhase: 'COMPETITIVE',
      status:      'new',
    }),
  ];
}
